### ISSUE TITLE
How much time do you have ? To make or make + play ?

### ISSUE THREAD

**Issue by MaryPek** [ludobox/ludobox.github.io#16]
Some users ask me How much time do they have to make a game or make + play ? Maybe we could just add How much do you have to craft or sthing like this ?

**Comment by clemsos** [comment]
The complicated part of this question is that “how much time it takes” depends on their skills and machines. If they know all machines super well and are super good then it is fast. If they are a bunch of 6y old kids it make take some more time.  

Maybe the right way will be to have a “level” option ? 
Like : beginner, rookie, average, senior, super-hero 
And people can level up as they build more games

**Comment by MaryPek** [comment]
Ah ok... i don't know maybe just in the text something more specific like How much time do you have to craft a game or something like this ?
