### ISSUE TITLE
Choose Age > not easy to select 

### ISSUE THREAD

**Issue by MaryPek** [ludobox/ludobox.github.io#18]
Better if we have the same design as choose your tools or language. It's not easy to click on this "thing" especially when you have just 3 choices. Not necessary...

**Comment by clemsos** [comment]
Yes the only goal was to be able to select multiple values, like Children+Teenagers for instance.

Is that useful ? 
If not, we can just turn the multi-select into a dropdown menu

**Comment by MaryPek** [comment]
Ah ok... just not easy to use maybe with check box ?
